### ISSUE TITLE
Class 'App\Providers\JetstrapFacade' not found

### ISSUE THREAD

**Issue by LfJohnVo** [nascent-africa/jetstrap#12]
**Describe the bug**

**To Reproduce**
1. Go to 'AppServiceProvider and add JetstrapFacade'

**Screenshots**

**Comment by tsommie** [comment]
Even though your explanation isn't clear, but it sounds to me like you need to import it.

```php
NascentAfrica\Jetstrap\JetstrapFacade;
```

If that doesn't work, then run `composer dump-autoload` and then try again

**Comment by tsommie** [comment]
Am going to close this on the assumption one of the above suggestions fixed your problem.
