### ISSUE TITLE
Too few arguments to function Livewire\LivewireManager::mount(), 0 passed in /var/www/mvp/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 261

### ISSUE THREAD

**Issue by VCollins** [nascent-africa/jetstrap#15]
**Describe the bug**
The mount method of the LivewireManager class fails to function properly if no Livewire component argument is passed from the __callStatic function in vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php. It is expecting an argument for a component, but isn't getting anything.

**To Reproduce**
1. Create a route for a page in routes/web.php that uses middleware for authentication
2. Create a page using a Livewire component in it, as in:
@extends('layouts.app')
@section('content')
@livewire('component') -> livewire component loaded here.
@stop
3. Attempt to navigate to the page in a browser

**Expected behavior**
The page should load with the Livewire component displaying correctly, after authenticating the logged-in user.

**Desktop (please complete the following information):**
 - OS: Windows 10 Professional
 - Browser: Firefox 83.0

**Smartphone (please complete the following information):**
 - Device: N/A
 - OS: N/A
 - Browser: N/A
 - Version: N/A

**Comment by tsommie** [comment]
I don't think this is an issue for Jetstrap because it doesn't alter the code of the component class or that of Jetstream, it simply replaces the front end part.

**Comment by VCollins** [comment]
Ok, so if the front end part is supposed to send livewire component objects through after a user has logged in (as the error message would indicate), is the facade management perhaps not passing something along to the next function (the mount function)?

I do understand that this may be an update issue with either Livewire or Jetstream, but this problem with the error message occured after I updated Jetstrap to v1.4.1

**Comment by tsommie** [comment]
The steps you took to describe the issue shows your having the problem in a livewire component you created, Jetstrap works well with the current setup of Jetstraam. please check your newly added code carefully.

**Comment by VCollins** [comment]
I will investigate the issue further. If it arises again, I will open a new issue. Thank you for the advice so far!
