### ISSUE TITLE
Error in v-on handler: "TypeError: Cannot read property 'querySelector' of null

### ISSUE THREAD

**Issue by singlepack** [nascent-africa/jetstrap#16]
Hello, after "php artisan jetstrap:swap inertia" don't work modal window. i'm use bootstrap 4 and admin lte 3

JetstrapFacade::bootstrap4();
JetstrapFacade::useAdminLte3();

https://prnt.sc/vw8l3l

**Comment by tsommie** [comment]
I need more details please, like what action are you expecting that triggers the error and more.

**Comment by singlepack** [comment]
When you click on the enable 2fa button, the modal window does not pop up.
See screenshots.
https://prnt.sc/vwrdee
https://prnt.sc/vwrds3

**Comment by singlepack** [comment]
The problem has been resolved. AppLoyaut.js was missing some code:
<portal-target name="modal" multiple>
</portal-target>
