### ISSUE TITLE
Support for Jetstream 2.0

### ISSUE THREAD

**Issue by gcaraciolo** [nascent-africa/jetstrap#18]
**Is your feature request related to a problem? Please describe.**
When we perform the Instructions to Install Jetstrap, it suggests to install Jetstram with its latest version. However, this packages seems to work only with Jetstram:1.6 and Jetstream's new version is 2.0.

**Describe the solution you'd like**
The project should points to the specific version it supports or made the upgrade. Also this should be in the documentation

**Comment by chrisV92** [comment]
It is not working in Jetstream 2.0

**Comment by tsommie** [comment]
Installing the new Jetstrap 2.x will fix this issue. Thank you for using the package and sorry for the late update!
