### ISSUE TITLE
Cannot install on laravel v8.5.7

### ISSUE THREAD

**Issue by zaheen** [nascent-africa/jetstrap#19]
**I tried to install jetstrap on laravel v8.5.7 and I got this issue.**
Problem 1
    - Installation request for nascent-africa/jetstrap ^1.4 -> satisfiable by nascent-africa/jetstrap[v1.4, v1.4.1].
    - Can only install one of: laravel/jetstream[1.x-dev, v2.0.3].
    - Can only install one of: laravel/jetstream[v2.0.3, 1.x-dev].
    - Can only install one of: laravel/jetstream[1.x-dev, v2.0.3].
    - Conclusion: install laravel/jetstream 1.x-dev
    - Installation request for laravel/jetstream (locked at v2.0.3, required as ^2.0) -> satisfiable by laravel/jetstream[v2.0.3].

**To Reproduce**
How can we fix this issue?

**Comment by tsommie** [comment]
This is because the old version of Jetstrap is locked at v1.x of Jetstream, installing the new Jetstrap 2.x will fix this issue.

**Comment by zaheen** [comment]
How can we fix it? I just downloaded latest version of laravel & jetstream.

**Comment by zaheen** [comment]
> This is because the old version of Jetstrap is locked at v1.x of Jetstream, installing the new Jetstrap 2.x will fix this issue.

How can I install new Jetstrap 2.x?
