### ISSUE TITLE
2 Factor Authentication Ignored

### ISSUE THREAD

**Issue by klexas** [nascent-africa/jetstrap#20]
**Describe the bug**
2 Factor Authentication is skipped completely 

**To Reproduce**
Register an account in application
Proceed to Profile section
Enable 2 factor auth
Sign out 
Log in again
- 2 Factor Authentication is ignored. And user proceed without challenge.

**Expected behavior**
2 Factor Challenge should be prompted

**Additional context**
I did check all enabled features, updated the 
                <form method="POST" action="/two-factor-challenge">

               action="{{ route('two-factor.login') }}

I'm not familiar enough with the fortify to know whats happening.

**Comment by tsommie** [comment]
Are you using livewire or inertia?

**Comment by vernk** [comment]
Two factor is not working correctly on Livewire 

It should make the user enter the code to verify when enabling it

**Comment by tsommie** [comment]
I haven't taken a deep look at it yet but I think the problem is caused by the missing `app.js` script that contains alpine.js which handles the automation in the page.
 
Add the below tag in your guest.blade.php head section and let me know if it does the trick.

```
<script src="{{ mix('js/app.js') }}" defer></script>
```

**Comment by vernk** [comment]
Yes that solved that bug, but what about making them enter their code, before 2FA is actually enabled. To make sure their device is paired? Almost all websites do this 

As if they enable it and don't pair, they will be locked out of their account

**Comment by vernk** [comment]
https://github.com/laravel/jetstream/issues/74 

Found this issue Jetstream so maybe its a feature request?

**Comment by tsommie** [comment]
Ok, a new tag has been released to address this issue [v2.1.4](https://github.com/nascent-africa/jetstrap/tree/v2.1.4). Thanks

**Comment by laravel-user-x** [comment]
Hi, I'm still not getting the 2fa screen after 2fa is enabled. I have the latest 2.1.5 update.

**Comment by paolocaccavo** [comment]
Yes, I am having the same issue with Laravel 9, PHP 8.1, jetstrap v2.5.4, jetstream v2.7.1

two_factor_confirmed_at just doesn't get written in the DB and stays null.
