### ISSUE TITLE
Unable to "npm run dev" on AdminLTE3 Presets, $grid-breakpoints problem.

### ISSUE THREAD

**Issue by wafiqamrillah** [nascent-africa/jetstrap#24]
Hello, sorry for my bad english.

So, I found some problems when I installed this package with AdminLTE3 presets. After running `npm install`, I run `npm run dev` in my terminal. The error logs like this.

> ERROR in ./resources/sass/admin-lte.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Undefined variable.
   ╷
62 │ @each $breakpoint in map-keys($grid-breakpoints) {
   │                               ^^^^^^^^^^^^^^^^^
   ╵
  resources\sass\_custom.scss 62:31  @import
  D:\project\project\resources\sass\admin-lte.scss 13:9                         root stylesheet
    at processResult (D:\project\project\node_modules\webpack\lib\NormalModule.js:597:19)
    at D:\project\project\node_modules\webpack\lib\NormalModule.js:691:5
    at D:\project\project\node_modules\loader-runner\lib\LoaderRunner.js:399:11
    at D:\project\project\node_modules\loader-runner\lib\LoaderRunner.js:251:18
    at context.callback (D:\project\project\node_modules\loader-runner\lib\LoaderRunner.js:124:13)
    at D:\project\project\node_modules\sass-loader\dist\index.js:73:7
    at Function.call$2 (D:\project\project\node_modules\sass\sass.dart.js:91074:16)
    at _render_closure1.call$2 (D:\project\project\node_modules\sass\sass.dart.js:79963:12)
    at _RootZone.runBinary$3$3 (D:\project\project\node_modules\sass\sass.dart.js:27185:18)
    at _FutureListener.handleError$1 (D:\project\project\node_modules\sass\sass.dart.js:25713:19)
  1 ERROR in child compilations
webpack compiled with 2 errors
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `mix`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
  npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\wafiq\AppData\Roaming\npm-cache\_logs\2021-01-18T02_43_12_492Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
  npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\wafiq\AppData\Roaming\npm-cache\_logs\2021-01-18T02_43_12_545Z-debug.log

So, I look the `resources\sass\_custom.scss` files, and I look `$grid-breakpoints` variable. I didn't find the variable's source.

Please fix this. Or, please give me some advice to solve this problem.

Big Thanks from me.

**Comment by tsommie** [comment]
That happens because bootstrap scss variables (_variables.scss) is not used when using AdminLte or CoreUi. You can remove block of code from line 62 to 72 in the _custom.scss fill to fix this problem. Will fix this in the next update.

**Comment by tsommie** [comment]
v2.1.3 has this issue fixed.
