### ISSUE TITLE
Two factor is broken

### ISSUE THREAD

**Issue by vernk** [nascent-africa/jetstrap#25]
**Describe the bug**
When they register their two factor device they need to first confirm their code to enable two factor. It allows them to enable it without pairing their device. This is like if you allowed someone to enter their phone number but not verify it with a code. 

**To Reproduce**
Register, enable two factor 

**Expected behavior**
It should prompt you after pairing to enter the code on your device , before it fully enables

**Comment by tsommie** [comment]
Please checkout issue [#20](https://github.com/nascent-africa/jetstrap/issues/20)
