### ISSUE TITLE
2fa screen not showing 

### ISSUE THREAD

**Issue by laravel-user-x** [nascent-africa/jetstrap#28]
I posted this in the existing closed 2fa issue thread so wasn't sure if I needed to create a new issue or not. Apologies if I didn't need to.

The issue I'm encountering is that I'm still not getting the 2fa screen during the login process after 2fa is enabled. I have the latest 2.1.5 update and I am using the livewire stack. I can see the app.js script is included within the guest.blade.php head tag but once I enable 2fa and then try and undertake the login process, it takes me straight to the dashboard without showing the 2fa screen once I have entered my email and password.

**Comment by tsommie** [comment]
Logic, redirects, and others are strictly Jetstream, but I will look into this.

**Comment by achmadhadikurnia** [comment]
Yes. its not worked for me too.

**Comment by tsommie** [comment]
There is a new tag release with changes that should address this issue, if you're still having the same problem feel free to reopen this issue.
