### ISSUE TITLE
Profile - remove photo not working

### ISSUE THREAD

**Issue by j-codes-4** [nascent-africa/jetstrap#3]
On the profile page, removing added photo is not working.
Clicking the button results in no action and throws errors in the console.
This error is present from selecting the inertia scaffolding with bootstrap4 views. Unsure about others

1. Go to profile page
2. Upload a photo and Save
3. Click remove photo

**Expected behavior**
Photo should be removed

**Screenshots**
Screenshot below highlights the missing code, adding it back fixes the problem.

resources/js/Pages/Profile/UpdateProfileInformationForm.vue
![githubIssue](https://user-images.githubusercontent.com/72002584/94937558-ba7c0a80-049d-11eb-8075-bc318d30c861.png)

**Comment by tsommie** [comment]
I've added the method and drafted a new release. Thank you for spotting the issue and thank you for using this package!

**Comment by j-codes-4** [comment]
No problem!
Thank you for making this package, such a time saver.
