### ISSUE TITLE
HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

### ISSUE THREAD

**Issue by achmadhadikurnia** [nascent-africa/jetstrap#30]
**Describe the bug**
How to fix and clear this error?
![image](https://user-images.githubusercontent.com/4408971/107584562-40b81280-6c2f-11eb-8a66-df9869c294a6.png)

**Comment by tsommie** [comment]
If you find a solution to this problem please give me a feedback
