### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'aside' of undefined

### ISSUE THREAD

**Issue by samuelhgf** [nascent-africa/jetstrap#34]
**Describe the bug**
I am receiving this error on the console and the page is not loaded

`Uncaught (in promise) TypeError: Cannot read property 'aside' of undefined
    at Proxy.hasSlot (app.js:16985)
    at Proxy.render (app.js:19968)
    at renderComponentRoot (app.js:6300)
    at componentEffect (app.js:9784)
    at reactiveEffect (app.js:4644)
    at effect (app.js:4619)
    at setupRenderEffect (app.js:9767)
    at mountComponent (app.js:9726)
    at processComponent (app.js:9686)
    at patch (app.js:9313)`

**To Reproduce**
Fresh installation of jetstream with inertia and --teams options
Register a user and will be redirect to /dashboard and then the page is not loaded and this error appears at the console

**Comment by tsommie** [comment]
What Preset are you using?

**Comment by amadorrojas** [comment]
I have the same error

**Comment by amadorrojas** [comment]
<div v-show="hasSlot('aside')" class="col-lg-3">
              <slot name="aside"></slot>
            </div>

Here is the problem, I commented it and it worked.
but I'm not sure if it's the right thing to do.

**Comment by samuelhgf** [comment]
@tsommie I'm using inertia with --teams

Could you see what @amadorrojas wrote above?

**Comment by amadorrojas** [comment]
@tsommie That portion of the code I attached, I simply commented it, I didn't write anything additional in the code.

**Comment by tsommie** [comment]
> @tsommie I'm using inertia with --teams
> 
> Could you see what @amadorrojas wrote above?

Yes...this issue will be fixed in the next update.

**Comment by tsommie** [comment]
I removed the `!!this.$scopedSlots[ name ]` logic from the `hasSlot` function, leaving just `!!this.$slots[ name ]`. Thats what caused the error.
