### ISSUE TITLE
Undefined variable: header

### ISSUE THREAD

**Issue by nhoxbin** [nascent-africa/jetstrap#38]
Hi!!
![image](https://user-images.githubusercontent.com/49804912/114234820-7cf6bd80-99a9-11eb-9f8d-2dc543a2a421.png)

dashboard blade
```
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4 font-weight-bold">
            {{ __('Dashboard') }}
        </h2>
    </x-slot>
</x-app-layout>
```

Test blade
```
<x-app-layout>
    <x-slot name="header">
        <h2 class="h4 font-weight-bold">
            {{ __('Test') }}
        </h2>
    </x-slot>
</x-app-layout>
```

I debug $header in Dashboard and Test, its the same. Its not different, but why is it doesn't run?

**Comment by tsommie** [comment]
Which preset are you using?

**Comment by nhoxbin** [comment]
I'm using `JetstrapFacade::useAdminLte3();`

**Comment by tsommie** [comment]
I don't know what page you are trying to view, but it should include:

```
<x-slot name="header">
        <h2 class="h4 font-weight-bold">
            {{ __('Test') }}
        </h2>
</x-slot>
```
Or, go to the `app.blade.php` and change `{{ $header }}` to `{{ $header ?? '' }}`, this way when a header is not defined in the page, PHP won't complain.

**Comment by nhoxbin** [comment]
> I don't know what page you are trying to view, but it should include:
> 
> ```
> <x-slot name="header">
>         <h2 class="h4 font-weight-bold">
>             {{ __('Test') }}
>         </h2>
> </x-slot>
I have included this line in my view and its not working
