### ISSUE TITLE
Admin lte3 sidebar menu

### ISSUE THREAD

**Issue by unknown-coder-1** [nascent-africa/jetstrap#39]
I think there is a bug. Adminlte3 **Main Sidebar Component** toggling does not work on the first login attempt. It requires reloading the page. After reloading it works. Can you please help me to fix that?
![screenshot](https://user-images.githubusercontent.com/82487716/114683678-2ee80e00-9d4b-11eb-9cd7-c1d15ac12eaa.gif)

**Comment by joesoeph** [comment]
I have the same issues... 😥

**Comment by unknown-coder-1** [comment]
@joesoeph I hope there will be a solution soon. 😥

**Comment by tsommie** [comment]
...will take a look, is this with inertia or liverwire?

**Comment by unknown-coder-1** [comment]
@tsommie it is with **inertia**

**Comment by tsommie** [comment]
> @tsommie it is with **inertia**

ok

**Comment by unknown-coder-1** [comment]
@tsommie I really like your work and want to continue with that. Sorry for asking again, did you have a chance to check it?

**Comment by tsommie** [comment]
> @tsommie I really like your work and want to continue with that. Sorry for asking again, did you have a chance to check it?

Yes, I did...have a few ideas what the problem might be but not sure yet, however am still working on it and other bug fixes, to be published soon. I appreciate your trust in the package, thank you.

**Comment by unknown-coder-1** [comment]
@tsommie thank you very much and sorry to be such **annoying**. I just checked, CoreUI also have the same issue. Could you please consider it when you fix it? Thank you again.

**Comment by REJack** [comment]
I know where the problem comes from, after Login/on Switching to Dashboard some AdminLTE Plugins need to be initialized (at least Layout & PushMenu).

**Comment by unknown-coder-1** [comment]
@REJack thank you for your comment. Do you know how or where to initialize it? The same also happens with **CoreUI**. Do you think both of them come from this issue?

**Comment by tsommie** [comment]
> @REJack thank you for your comment. Do you know how or where to initialize it? The same also happens with **CoreUI**. Do you think both of them come from this issue?

I just published a new release, try this and see if the problem still persists, cause this issue didn't occur in my dev setup.

**Comment by unknown-coder-1** [comment]
@tsommie thank you for your hard work. I checked that. It is better than before. At least now it works during logout and login. But the same issue happens in incognito mode. :(

**Comment by tsommie** [comment]
> > @REJack thank you for your comment. Do you know how or where to initialize it? The same also happens with **CoreUI**. Do you think both of them come from this issue?
> 
> I just published a new release, try this and see if the problem still persists, cause this issue didn't occur in my dev setup.

Ok...will look into it.
