### ISSUE TITLE
Modal Open and Close error

### ISSUE THREAD

**Issue by arnaldovalente** [nascent-africa/jetstrap#43]
Tank you for your greatest job.

In my page I have many model.
In jetstream I can use the same variable name for open the different modal, all modal start from event emit from parent page and are located in different modal child. With your implementation I need to use different name between child modal for toogle show variable.

About this not big problem, I will rename the variable to be unique.

The big problem is when i close the model.
If I use the bottom button there's no problem for close and reopen the same or another modal,
but if I click on the X on top of the modal or I click outside I can't reopen any modal.

I have the same problem in profile page with the "Two Factor Authentication" modal and "Browser Sessions" modal.

Sorry but I can't help you to fix issue, I'm beginner.

**Comment by arnaldovalente** [comment]
Sorry, I'm wrong

I can open the other modal but not the same if I click outside or I click the X in top of modal

**Comment by arnaldovalente** [comment]
First open of modal:
{"effects":{"html":null,"dispatches":[{"event":"confirming-logout-other-browser-sessions","data":null}],"dirty":["confirmingLogout"]},"serverMemo":{"data":{"confirmingLogout":true},"checksum":"d35eabe17e38c1877694c47352623d820e9360defea282fbc9d18c294de381d8"}}

Second after close modal with click outside:
{"effects":{"html":null,"dispatches":[{"event":"confirming-logout-other-browser-sessions","data":null}],"dirty":[]},"serverMemo":{"checksum":"d35eabe17e38c1877694c47352623d820e9360defea282fbc9d18c294de381d8"}}

**Comment by tsommie** [comment]
Is the issue resolved or not?

**Comment by arnaldovalente** [comment]
No. If you open a modal and don't close with wire call the modal dosen't open anymore.

**Comment by arnaldovalente** [comment]
$watch('show', value => {
      if (value) {
          modal.modal({backdrop: 'static'});
          modal.modal('show');
      } else {
          modal.modal('hide');
      }
  });

The else statement is never fired when click outside or click the X button.
I disable the outside click (add on line 3) and removed the close button from dialog, a workaround waiting for solution

**Comment by arnaldovalente** [comment]
I find the solution
remove wire:ignore.self from modal
I submit the change

**Comment by arnaldovalente** [comment]
Where I write that the problem is refered to livewire??? My english is poor but I never write this

**Comment by arnaldovalente** [comment]
And yes my PR fix what I write about, but don't warry, if you don't want fix it I can close
