### ISSUE TITLE
Conflicts with Inertial-laravel 0.4.2

### ISSUE THREAD

**Issue by nakjemmy** [nascent-africa/jetstrap#45]
**Describe the bug**
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires inertiajs/inertia-laravel ^0.4.2, found inertiajs/inertia-laravel[v0.4.2] but the package is fixed to v0.3.6 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by tsommie** [comment]
This package moves with Jetstream, and not Jetstream dependencies. As a matter of fact, this package does not make any changes to your composer.json, and any changes your seeing in that file was made by Jetstream. So you can either move at the same pace as Jetstream or submit this issue to its repo.

Thanks a lot for using the package, and also trying to help make it better.

**Comment by nakjemmy** [comment]
Thanks for the response, Sir

I've gone through the dependencies to confirm your explanation.

Thank you for the clarification.
