### ISSUE TITLE
Will there be support for bootstrap 5 soon?

### ISSUE THREAD

**Issue by gasner** [nascent-africa/jetstrap#46]
Will there be support for bootstrap 5 soon? 🙏

**Comment by tsommie** [comment]
Hopefully yes. But migrating to Bootstrap 5 from the initial Jetstrap swap is straightforward.

1. Upgrade to Bootstrap 5
2. Remove JQuery
3. Remove all "form-row", "form-group" from the forms and input field and replace them with the "g", "mb" utilities.
3. Open and close all modals like this:  `var myModal = new bootstrap.Modal(document.getElementById('myModal'), options)`.
4. The close modal button in B5 is different I think so you might want to take a look at that also.

And that's pretty much it.
