### ISSUE TITLE
Error: Cannot find module 'node-sass'

### ISSUE THREAD

**Issue by deanzod** [nascent-africa/jetstrap#49]
Every time I try a fresh install of laravel, jetstream and jetstrap I get a node-sass error. (I don't get this without jetstrap)

```
ERROR in ./resources/sass/app.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ../../node_modules/sass-loader/lib/loader.js):
Error: Cannot find module 'node-sass'

```

**To Reproduce**
1. install laravel
2. install jetstream +livewire
3. install jetstrap
4. perform swap
5. npm install
6. npm run dev

**Comment by tsommie** [comment]
I've never experienced this before, and the steps you described are basically the way I use Jetstrap 100% of the time. I'll look into it.

**Comment by deanzod** [comment]
I eventually fixed this by installing `sass-loader` - not sure why it gets removed?

**Comment by tsommie** [comment]
> I've never experienced this before, and the steps you described are basically the way I use Jetstrap 100% of the time. I'll look into it.

Was it caused by Jetstrap installation?

**Comment by deanzod** [comment]
Yes. I installed laravel (composer method) and jetstream with livewire. Then npm install (then ran npm run dev and it was fine). Then installed jetstrap and swapped, then npm install again followed by npm run dev and get the error. I also tried the same steps but without doing the npm steps in the middle and still got the same error. 

It says it can't find node-sass module but it seems to just be because sass-loader is missing.

I'm thinking the jetstrap npm install removes sass-loader for some reason

I'm on node v14 btw

**Comment by tsommie** [comment]
Ok, thanks for the observation.

**Comment by tsommie** [comment]
Sass-loader is added to your package.json the first time you run any of the laravel-mix compilation script, and this should be done after running all Jetstrap commands. I've done this over and over and still not able to get this issue, the sass-loader is never missing in my code.
