### ISSUE TITLE
Undefined variable $slot

### ISSUE THREAD

**Issue by tahayasen55** [nascent-africa/jetstrap#51]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by tsommie** [comment]
Even though your issue is not clear in any way, am sure it's a mistake on your part.


As soon as the resources are published to your application, whatever modification you make to it that results to issues like this can not be fixed by us. 

Thanks for using the package.
