### ISSUE TITLE
I can´t use with Bootstrap 4

### ISSUE THREAD

**Issue by inkael** [nascent-africa/jetstrap#65]
How can I use jetstrap with Bootstrap 4, I know rigth now Bootstrap 5 is default but how can I change it? I tried with JetstrapFacade::bootstrap4(); but I got a error Call to undefined method NascentAfrica\Jetstrap\Jetstrap::bootstrap4() 

Merci

**Comment by REJack** [comment]
If I'm not wrong, you need to use v2.4, since v2.5+ is BS5 not BS4

**Comment by inkael** [comment]
You´re right I use that version and it works  thanks
