### ISSUE TITLE
Class "Inertia\Inertia" not found

### ISSUE THREAD

**Issue by enaeim** [nascent-africa/jetstrap#70]
Hi.

I create a raw Laravel project and then I came to the nascent-africa/jetstrap package tutorial. I executed all the commands in order until the "Finalizing The Installation" section.

It means as follows:

`composer require laravel/jetstream`

`composer require nascent-africa/jetstrap --dev`

`php artisan jetstrap:swap livewire` or `php artisan jetstrap:swap inertia`

`npm install && npm run dev`

`php artisan migrate`

But not existing login or register controller or blade files on project. And then I again run all above commands and this time encounter this error message:

![image](https://user-images.githubusercontent.com/33656061/142730255-ca6b1f7e-f351-4748-9909-65f8e86c7dc9.png)

Please help me.

Thaks a lot.

**Comment by enaeim** [comment]
It was my own fault.

**Comment by AurelianSpodarec** [comment]
And what did you do to fix this?

**Comment by enaeim** [comment]
> nascent-africa/jetstrap

I did not execute one of the required basic commands

**Comment by enaeim** [comment]
> And what did you do to fix this?

I did not execute one of the required basic commands.

**Comment by komalv081** [comment]
For installing Jetstream , 
**composer require laravel/jetstream**
**php artisan jetstream: install livewire**  and i think you forgot to run the second command

**Comment by srikanthtelkalapally888** [comment]
can you explain the solution for this ? if you have any  solutions .. 
because Iam also facing this problem

**Comment by InternetFacilito** [comment]
php artisan jetstream:install livewire

**Comment by rahmanpoor** [comment]
Note that this path does not recognize Inertia class.
vendor/laravel/jetstream/src/Http/Middleware/ShareInertiaData.php:23

You should add this class by this command:
**composer require inertiajs/inertia-laravel**

The problem will be solved and enjoy.
