### ISSUE TITLE
AdminLTE3 Preset

### ISSUE THREAD

**Issue by joshua161** [nascent-africa/jetstrap#71]
No logout feature

**Comment by allgood** [comment]
Having same problem here, I think that the problem is on loading bootstrap javascript functionality since the user drop down menu doesn't work

**Comment by allgood** [comment]
Solved it here:

needed to edit `resources/views/vendor/jetstream/components/dropdown.blade.php` and change `data-bs-toggle` to `data-toggle`

`data-bs-toggle` is specific to bootstrap 5 and the project is installing bootstrap 4.

**Comment by sicaboy** [comment]
Nav team/profile dropdown doesn't work in AdminLTE
