### ISSUE TITLE
Confirm password modal on "Browser Sessions" and "Delete Account" dont show error message when submit empty password.

### ISSUE THREAD

**Issue by vanthao03596** [nascent-africa/jetstrap#9]
**Describe the bug**
.

**To Reproduce**
1. Go to profile page
2. Click on "Logout other browser session" and leave empty password.
3. Click "Logout Other Browser Sessions" button

**Expected behavior**
Show error message when submit empty password

**Desktop (please complete the following information):**
 - OS: ubuntu 20
 - Browser: Chrome

**Comment by tsommie** [comment]
Are you using the livewire or inertia setup?

**Comment by vanthao03596** [comment]
@tsommie i'm using livewire.

**Comment by tsommie** [comment]
Ok, I've seen the issue with the browser session and you can fix it by adding `class="{{ $errors->has('password') ? 'is-invalid' : '' }}"` to your passworrd input componenent like so:
```
<x-jet-input type="password" placeholder="{{ __('Password') }}"
                                 x-ref="password"
                                 class="{{ $errors->has('password') ? 'is-invalid' : '' }}"
                                 wire:model.defer="password"
                                 wire:keydown.enter="logoutOtherBrowserSessions" />
```

However the User delete account works just fine, am I missing something?

**Comment by vanthao03596** [comment]
I created gif. As you see confirm modal shouldn't hide
![Screencast from 23-10-2020 20_28_37](https://user-images.githubusercontent.com/34786441/97009782-bc059380-156e-11eb-9c55-4d46b968be14.gif)

**Comment by tsommie** [comment]
Ok, I get it now. am aware of this issue and I haven't been able to find a workaround for it. It works fine when using Inertia but the problem with Livewire is that when you perform a livewire action the modal disappears leaving just the backdrop and will require a page refresh before it can go away. but adding the `data-dismiss="modal" ` to the `Logout Other Browser Sessions` button to make sure everything disappears, but if you click on  `Logout Other Browser Sessions` again the modal will appear with the errors. Am still working to fix it but If you have any suggestions am more than ready to try it out.

**Comment by ShadyAlfred** [comment]
Maybe you can verify if it's empty or not using Javascript. In case of it being empty, the modal won't be dismissed and will show the error.

**Comment by mcvphp** [comment]
change data-dissmis="modal" to `data-dismiss="{{ $errors->has('password') ? 'modal' : '' }}"`

**Comment by tsommie** [comment]
@mcanv Please can i get more details?
